---
title: "Understanding Retail Consumers Behaviour"
author: "Rihad Variawa"
date: "2019-04-11"
output: html_document
summary: 'Understanding consumer behaviour'
header:
  image: 'headers/tl.jpg'
---



<p>Clustering can be used for market segmentation, the idea of dividing airline passengers into small, more similar groups, and then designing a marketing strategy specifically for each group. In this analysis, I’ll see how this idea can be applied to <strong>retail consumer data.</strong></p>
<p>I’ll use the dataset Households.csv.xz, which contains data collected over two years for a group of 2,500 households. Each row (observation) in our dataset represents a unique household. The dataset contains the following variables:</p>
<ul>
<li>NumVisits = the number of times the household visited the retailer</li>
<li>AvgProdCount = the average number of products purchased per transaction</li>
<li>AvgDiscount = the average discount per transaction from coupon usage
(in %) - NOTE: Do not divide this value by 100!</li>
<li>AvgSalesValue = the average sales value per transaction</li>
<li>MorningPct = the percentage of visits in the morning (8am - 1:59pm)</li>
<li>AfternoonPct = the percentage of visits in the afternoon (2pm - 7:59pm)</li>
</ul>
<p>Note that some visits can occur outside of morning and afternoon hours. That is, visits from 8pm - 7:59am are possible.</p>
<p>This dataset was derived from source files provided by <strong>dunnhumby,</strong> a customer science company based in the UK.</p>
<div id="problem-1---reading-in-the-data" class="section level3">
<h3>Problem 1 - Reading in the data</h3>
<p>Read the dataset Households.csv.xz into R.</p>
<pre class="r"><code>HouseHolds &lt;- read.csv(&quot;Households.csv.xz&quot;)
str(HouseHolds)</code></pre>
<pre><code>## &#39;data.frame&#39;:    2500 obs. of  6 variables:
##  $ NumVisits    : int  86 45 47 30 40 250 59 113 20 9 ...
##  $ AvgProdCount : num  20.08 15.87 19.62 10.03 5.55 ...
##  $ AvgDiscount  : num  8.11 7.44 14.37 3.85 2.96 ...
##  $ AvgSalesValue: num  50.4 43.4 56.5 40 19.5 ...
##  $ MorningPct   : num  46.51 8.89 14.89 13.33 2.5 ...
##  $ AfternoonPct : num  51.2 60 76.6 56.7 67.5 ...</code></pre>
<pre class="r"><code>summary(HouseHolds)</code></pre>
<pre><code>##    NumVisits       AvgProdCount     AvgDiscount     AvgSalesValue    
##  Min.   :   1.0   Min.   : 1.186   Min.   : 0.089   Min.   :  2.388  
##  1st Qu.:  39.0   1st Qu.: 6.123   1st Qu.: 3.006   1st Qu.: 18.329  
##  Median :  79.0   Median : 8.979   Median : 4.865   Median : 27.417  
##  Mean   : 110.6   Mean   :10.291   Mean   : 5.713   Mean   : 31.621  
##  3rd Qu.: 142.2   3rd Qu.:13.116   3rd Qu.: 7.327   3rd Qu.: 40.546  
##  Max.   :1300.0   Max.   :56.600   Max.   :47.176   Max.   :165.829  
##    MorningPct      AfternoonPct   
##  Min.   :  0.00   Min.   :  0.00  
##  1st Qu.: 16.67   1st Qu.: 42.20  
##  Median : 26.09   Median : 52.00  
##  Mean   : 28.73   Mean   : 51.45  
##  3rd Qu.: 37.17   3rd Qu.: 61.29  
##  Max.   :100.00   Max.   :100.00</code></pre>
<pre class="r"><code>head(HouseHolds)</code></pre>
<pre><code>##   NumVisits AvgProdCount AvgDiscount AvgSalesValue MorningPct AfternoonPct
## 1        86     20.08140    8.105116      50.35070  46.511628     51.16279
## 2        45     15.86667    7.444222      43.42978   8.888889     60.00000
## 3        47     19.61702   14.365106      56.45128  14.893617     76.59574
## 4        30     10.03333    3.855000      40.00367  13.333333     56.66667
## 5        40      5.55000    2.958250      19.47650   2.500000     67.50000
## 6       250      7.16400    3.313360      23.98464  25.600000     61.20000</code></pre>
<p>How many households have logged transactions at the retailer only in the morning?</p>
<pre class="r"><code>nrow(subset(HouseHolds, MorningPct == 100))</code></pre>
<pre><code>## [1] 4</code></pre>
<p>How many households have logged transactions at the retailer only in the afternoon?</p>
<pre class="r"><code>nrow(subset(HouseHolds, AfternoonPct == 100))</code></pre>
<pre><code>## [1] 13</code></pre>
</div>
<div id="problem-2---descriptive-statistics" class="section level3">
<h3>Problem 2 - Descriptive statistics</h3>
<p>Of the households that spend more than $150 per transaction on average, what is the minimum average discount per transaction?</p>
<pre class="r"><code>min(subset(HouseHolds, AvgSalesValue &gt; 150)$AvgDiscount)</code></pre>
<pre><code>## [1] 15.64607</code></pre>
<p>Of the households who have an average discount per transaction greater than 25%, what is the minimum average sales value per transaction?</p>
<pre class="r"><code>min(subset(HouseHolds, AvgDiscount &gt; 25)$AvgSalesValue)</code></pre>
<pre><code>## [1] 50.1175</code></pre>
<p>What proportion of households visited the retailer at least 300 times?</p>
<pre class="r"><code>nrow(subset(HouseHolds, NumVisits &gt;= 300)) / nrow(HouseHolds)</code></pre>
<pre><code>## [1] 0.0592</code></pre>
</div>
<div id="problem-3---importance-of-normalizing" class="section level3">
<h3>Problem 3 - Importance of Normalizing</h3>
<p>When clustering data, its often important to normalize the variables so that they are all on the same scale.</p>
<p>If you clustered this dataset without normalizing, which variable would you expect to dominate in the distance calculations?</p>
<pre class="r"><code>summary(HouseHolds)</code></pre>
<pre><code>##    NumVisits       AvgProdCount     AvgDiscount     AvgSalesValue    
##  Min.   :   1.0   Min.   : 1.186   Min.   : 0.089   Min.   :  2.388  
##  1st Qu.:  39.0   1st Qu.: 6.123   1st Qu.: 3.006   1st Qu.: 18.329  
##  Median :  79.0   Median : 8.979   Median : 4.865   Median : 27.417  
##  Mean   : 110.6   Mean   :10.291   Mean   : 5.713   Mean   : 31.621  
##  3rd Qu.: 142.2   3rd Qu.:13.116   3rd Qu.: 7.327   3rd Qu.: 40.546  
##  Max.   :1300.0   Max.   :56.600   Max.   :47.176   Max.   :165.829  
##    MorningPct      AfternoonPct   
##  Min.   :  0.00   Min.   :  0.00  
##  1st Qu.: 16.67   1st Qu.: 42.20  
##  Median : 26.09   Median : 52.00  
##  Mean   : 28.73   Mean   : 51.45  
##  3rd Qu.: 37.17   3rd Qu.: 61.29  
##  Max.   :100.00   Max.   :100.00</code></pre>
<div id="numvisits" class="section level4">
<h4>NumVisits</h4>
</div>
</div>
<div id="problem-4---normalizing-the-data" class="section level3">
<h3>Problem 4 - Normalizing the Data</h3>
<p>Normalize all of the variables in the dataset (Note that these codes assume that our dataset is called “Households”, and create the normalized dataset “HouseholdsNorm”. You can change the names to anything you want by editing the codes.)</p>
<pre class="r"><code>library(caret)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## Loading required package: ggplot2</code></pre>
<pre class="r"><code>preproc &lt;- preProcess(HouseHolds)
HouseHoldsNorm &lt;- predict(preproc, HouseHolds)</code></pre>
<p>(Remember that for each variable, the normalization process subtracts the mean and divides by the standard deviation. In our normalized dataset, all of the variables should have mean 0 and standard deviation 1.</p>
<pre class="r"><code>summary(HouseHoldsNorm)</code></pre>
<pre><code>##    NumVisits        AvgProdCount      AvgDiscount      AvgSalesValue    
##  Min.   :-0.9475   Min.   :-1.5239   Min.   :-1.4010   Min.   :-1.5342  
##  1st Qu.:-0.6190   1st Qu.:-0.6976   1st Qu.:-0.6743   1st Qu.:-0.6976  
##  Median :-0.2731   Median :-0.2197   Median :-0.2112   Median :-0.2206  
##  Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000   Mean   : 0.0000  
##  3rd Qu.: 0.2737   3rd Qu.: 0.4728   3rd Qu.: 0.4021   3rd Qu.: 0.4684  
##  Max.   :10.2828   Max.   : 7.7500   Max.   :10.3293   Max.   : 7.0432  
##    MorningPct       AfternoonPct     
##  Min.   :-1.6779   Min.   :-3.22843  
##  1st Qu.:-0.7047   1st Qu.:-0.58006  
##  Median :-0.1546   Median : 0.03458  
##  Mean   : 0.0000   Mean   : 0.00000  
##  3rd Qu.: 0.4926   3rd Qu.: 0.61755  
##  Max.   : 4.1617   Max.   : 3.04658</code></pre>
<p>What is the maximum value of NumVisits in the normalized dataset?
#### 10.2828</p>
<p>What is the minimum value of AfternoonPct in the normalized dataset?
#### -3.22843</p>
<p>Create a dendrogram of our data:</p>
<pre class="r"><code>set.seed(200)
distances &lt;- dist(HouseHoldsNorm, method = &quot;euclidean&quot;)
ClusterShoppers &lt;- hclust(distances, method = &quot;ward.D&quot;)
plot(ClusterShoppers, labels = FALSE)</code></pre>
<p><img src="/project/retail_consumers/retail_consumers_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="problem-5---interpreting-the-dendrogram" class="section level3">
<h3>Problem 5 - Interpreting the Dendrogram</h3>
<p>Based on the dendrogram, how many clusters do you think would be appropriate for this problem?
#### 2, 3, 5</p>
</div>
<div id="problem-6---k-means-clustering" class="section level3">
<h3>Problem 6 - K-means Clustering</h3>
<p>Run the k-means clustering algorithm on our normalized dataset, selecting 10 clusters. Right before using the kmeans function, Remember “set.seed(200)”.</p>
<pre class="r"><code>set.seed(200)
k &lt;- 10
KMC &lt;- kmeans(HouseHoldsNorm, centers = k, iter.max = 1000)
str(KMC)</code></pre>
<pre><code>## List of 9
##  $ cluster     : int [1:2500] 7 3 1 3 5 6 1 1 3 8 ...
##  $ centers     : num [1:10, 1:6] -0.248 -0.483 -0.234 -0.18 -0.246 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:10] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##   .. ..$ : chr [1:6] &quot;NumVisits&quot; &quot;AvgProdCount&quot; &quot;AvgDiscount&quot; &quot;AvgSalesValue&quot; ...
##  $ totss       : num 14994
##  $ withinss    : num [1:10] 628 449 700 282 580 ...
##  $ tot.withinss: num 4828
##  $ betweenss   : num 10166
##  $ size        : int [1:10] 246 51 490 118 504 226 141 284 52 388
##  $ iter        : int 5
##  $ ifault      : int 0
##  - attr(*, &quot;class&quot;)= chr &quot;kmeans&quot;</code></pre>
<pre class="r"><code>kmeansGroups &lt;- KMC$cluster
table(kmeansGroups)</code></pre>
<pre><code>## kmeansGroups
##   1   2   3   4   5   6   7   8   9  10 
## 246  51 490 118 504 226 141 284  52 388</code></pre>
<p>How many observations are in the smallest cluster?</p>
<pre class="r"><code>min(table(kmeansGroups))</code></pre>
<pre><code>## [1] 51</code></pre>
<div id="section" class="section level4">
<h4>51</h4>
<p>How many observations are in the largest cluster?</p>
<pre class="r"><code>max(table(kmeansGroups))</code></pre>
<pre><code>## [1] 504</code></pre>
</div>
<div id="section-1" class="section level4">
<h4>504</h4>
</div>
</div>
<div id="problem-7---understanding-the-clusters" class="section level3">
<h3>Problem 7 - Understanding the Clusters</h3>
<p>Now, use the cluster assignments from k-means clustering together with the cluster centroids to explore the next few questions.</p>
<pre class="r"><code>kmeans1 &lt;- subset(HouseHolds, kmeansGroups == 1)
kmeans2 &lt;- subset(HouseHolds, kmeansGroups == 2)
kmeans3 &lt;- subset(HouseHolds, kmeansGroups == 3)
kmeans4 &lt;- subset(HouseHolds, kmeansGroups == 4)
kmeans5 &lt;- subset(HouseHolds, kmeansGroups == 5)
kmeans6 &lt;- subset(HouseHolds, kmeansGroups == 6)
kmeans7 &lt;- subset(HouseHolds, kmeansGroups == 7)
kmeans8 &lt;- subset(HouseHolds, kmeansGroups == 8)
kmeans9 &lt;- subset(HouseHolds, kmeansGroups == 9)
kmeans10 &lt;- subset(HouseHolds, kmeansGroups == 10)

colMeans(kmeans1)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##      81.89431      19.11594      10.92924      59.49868      22.76746 
##  AfternoonPct 
##      61.93939</code></pre>
<pre class="r"><code>colMeans(kmeans2)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##      54.70588      32.62351      19.65784      99.73684      32.15593 
##  AfternoonPct 
##      49.41508</code></pre>
<pre class="r"><code>colMeans(kmeans3)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     83.508163     12.081068      6.881078     37.391552     25.609449 
##  AfternoonPct 
##     51.185788</code></pre>
<pre class="r"><code>colMeans(kmeans4)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     89.788136      7.053082      3.877403     21.175564     71.391580 
##  AfternoonPct 
##     22.584436</code></pre>
<pre class="r"><code>colMeans(kmeans5)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##      82.18254       5.89608       2.90764      17.51880      19.36659 
##  AfternoonPct 
##      55.03936</code></pre>
<pre class="r"><code>colMeans(kmeans6)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##    281.796460      8.117065      4.297144     25.446228     29.851517 
##  AfternoonPct 
##     51.583481</code></pre>
<pre class="r"><code>colMeans(kmeans7)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     99.886525     15.469831      9.343551     50.447122     53.462000 
##  AfternoonPct 
##     35.836861</code></pre>
<pre class="r"><code>colMeans(kmeans8)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     80.288732      9.992614      5.288399     29.327693     13.350751 
##  AfternoonPct 
##     74.066827</code></pre>
<pre class="r"><code>colMeans(kmeans9)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##    626.903846      5.203533      2.632325     16.278150     24.641085 
##  AfternoonPct 
##     48.731981</code></pre>
<pre class="r"><code>colMeans(kmeans10)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     70.729381      6.479314      3.527893     19.688575     37.377204 
##  AfternoonPct 
##     38.916046</code></pre>
<p>Which cluster best fits the description “morning shoppers stopping in to make a quick purchase”?
#### Cluster 4</p>
</div>
<div id="problem-8---understanding-the-clusters" class="section level3">
<h3>Problem 8 - Understanding the Clusters</h3>
<p>Which cluster best fits the description “shoppers with high average product count and high average value per visit”?
#### Cluster 2</p>
</div>
<div id="problem-9---understanding-the-clusters" class="section level3">
<h3>Problem 9 - Understanding the Clusters</h3>
<p>Which cluster best fits the description “frequent shoppers with low value per visit”?
#### Cluster 9</p>
</div>
<div id="problem-10---random-behavior" class="section level3">
<h3>Problem 10 - Random Behavior</h3>
<p>If we ran hierarchical clustering a second time without making any additional calls to set.seed, we would expect:
#### Identical results to the first hierarchical clustering</p>
<p>If we ran k-means clustering a second time without making any additional calls to set.seed, we would expect:
#### Different results from the first k-means clustering</p>
<p>If we ran k-means clustering a second time, again running the code set.seed(200) right before doing the clustering, we would expect:
#### Identical results to the first k-means clustering</p>
<p>If we ran k-means clustering a second time, running the code set.seed(100) right before doing the clustering, we would expect:
#### Different results from the first k-means clustering</p>
</div>
<div id="problem-11---the-number-of-clusters" class="section level3">
<h3>Problem 11 - The Number of Clusters</h3>
<p>Suppose the marketing department at the retail store decided that the 10 clusters were too specific, and they wanted more general clusters to describe the consumer base.</p>
<p>Would they want to increase or decrease the number of clusters?
#### Decrease the number of clusters</p>
</div>
<div id="problem-12---increasing-the-number-of-clusters" class="section level3">
<h3>Problem 12 - Increasing the Number of Clusters</h3>
<p>Run the k-means clustering algorithm again, this time selecting 5 clusters. Right before the “kmeans” function, set the random seed to 5000.</p>
<pre class="r"><code>set.seed(5000)
k &lt;- 5
KMC.5 &lt;- kmeans(HouseHoldsNorm, centers = k, iter.max = 1000)
str(KMC.5)</code></pre>
<pre><code>## List of 9
##  $ cluster     : int [1:2500] 5 5 1 5 2 2 5 5 5 2 ...
##  $ centers     : num [1:5, 1:6] -0.398 -0.193 -0.169 2.695 -0.176 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:5] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##   .. ..$ : chr [1:6] &quot;NumVisits&quot; &quot;AvgProdCount&quot; &quot;AvgDiscount&quot; &quot;AvgSalesValue&quot; ...
##  $ totss       : num 14994
##  $ withinss    : num [1:5] 1264 1838 1336 754 1604
##  $ tot.withinss: num 6795
##  $ betweenss   : num 8199
##  $ size        : int [1:5] 182 994 428 172 724
##  $ iter        : int 7
##  $ ifault      : int 0
##  - attr(*, &quot;class&quot;)= chr &quot;kmeans&quot;</code></pre>
<pre class="r"><code>kmeansGroups.5 &lt;- KMC.5$cluster
table(kmeansGroups.5)</code></pre>
<pre><code>## kmeansGroups.5
##   1   2   3   4   5 
## 182 994 428 172 724</code></pre>
<p>How many observations are in the smallest cluster?</p>
<pre class="r"><code>min(table(kmeansGroups.5))</code></pre>
<pre><code>## [1] 172</code></pre>
<div id="section-2" class="section level4">
<h4>172</h4>
<p>How many observations are in the largest cluster?</p>
<pre class="r"><code>max(table(kmeansGroups.5))</code></pre>
<pre><code>## [1] 994</code></pre>
</div>
<div id="section-3" class="section level4">
<h4>994</h4>
</div>
</div>
<div id="problem-13---describing-the-clusters" class="section level3">
<h3>Problem 13 - Describing the Clusters</h3>
<p>Use the cluster assignments from k-means clustering with 5 clusters, which cluster best fits the description “frequent shoppers with low value per visit”?</p>
<pre class="r"><code>kmeans1.5 &lt;- subset(HouseHolds, kmeansGroups.5 == 1)
kmeans2.5 &lt;- subset(HouseHolds, kmeansGroups.5 == 2)
kmeans3.5 &lt;- subset(HouseHolds, kmeansGroups.5 == 3)
kmeans4.5 &lt;- subset(HouseHolds, kmeansGroups.5 == 4)
kmeans5.5 &lt;- subset(HouseHolds, kmeansGroups.5 == 5)

colMeans(kmeans1.5)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##      64.60989      24.47666      14.69849      76.09221      31.49236 
##  AfternoonPct 
##      53.37519</code></pre>
<pre class="r"><code>colMeans(kmeans2.5)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     88.274648      6.573304      3.355126     19.679329     21.516913 
##  AfternoonPct 
##     53.900113</code></pre>
<pre class="r"><code>colMeans(kmeans3.5)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     91.095794      8.541218      4.910884     26.956499     54.594773 
##  AfternoonPct 
##     32.958057</code></pre>
<pre class="r"><code>colMeans(kmeans4.5)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##    422.273256      7.074807      3.710112     22.317813     27.386172 
##  AfternoonPct 
##     51.043708</code></pre>
<pre class="r"><code>colMeans(kmeans5.5)</code></pre>
<pre><code>##     NumVisits  AvgProdCount   AvgDiscount AvgSalesValue    MorningPct 
##     90.276243     13.628410      7.640804     41.803608     22.980428 
##  AfternoonPct 
##     58.626883</code></pre>
<div id="cluster-4" class="section level4">
<h4>Cluster 4</h4>
</div>
</div>
<div id="problem-14---understanding-centroids" class="section level3">
<h3>Problem 14 - Understanding Centroids</h3>
<p>Why do we typically use cluster centroids to describe the clusters?
#### The cluster centroid captures the average behavior in the cluster, and can be used to summarize the general pattern in the cluster.</p>
</div>
<div id="problem-15---using-a-visualization" class="section level3">
<h3>Problem 15 - Using a Visualization</h3>
<p>Which of the following visualizations could be used to observe the distribution of NumVisits, broken down by cluster?
#### - A box plot of the variable NumVisits, subdivided by cluster
#### - ggplot with NumVisits on the x-axis and the cluster number on the y-axis, plotting with geom_point()</p>
</div>
